spring:
  datasource:
    username: root
    password: qishimeiyoumima
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///openapi-admin?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
